version: '3'
services:

  ssdd-frontend:
    build: frontend/.
    ports:
      - 5010:5010
    env_file: sql.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_DEBUG=true
      - PORT=5010

  ssdd-llamachat:
    image: dsevilla/ssdd-llamachat:1.0
    ports:
      - 5020:5020

  db-mysql:
    build: db-mysql/.
    ports:
      - 3306:3306
    env_file: sql.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ssdd

  backend-rest:
    build: backend-rest/es.um.sisdist.backend.Service/.
    ports:
      - 8080:8080
    env_file: sql.env

  backend-grpc:
    build: backend-grpc/es.um.sisdist.backend.grpc.GrpcServiceImpl/.
    ports:
      - 50051:50051
    env_file: sql.env
